# .github/workflows/destroy.yml

name: Destruir Infraestrutura Terraform (Manual)

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: "projects/159248096205/locations/global/workloadIdentityPools/github-pool-a3/providers/github-provider"
          service_account: "strapi-deployer@sound-dialect-458215-j9.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        env:
          TF_VAR_app_keys: ${{ secrets.STRAPI_APP_KEYS }}
          TF_VAR_api_token_salt: ${{ secrets.secrets.STRAPI_API_TOKEN_SALT }}
          TF_VAR_admin_jwt_secret: ${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
          TF_VAR_jwt_secret: ${{ secrets.STRAPI_JWT_SECRET }}
          TF_VAR_transfer_token_salt: ${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}
        run: terraform destroy -auto-approve -var="strapi_image=dummy"
        working-directory: ./terraform