# .github/workflows/destroy.yml

name: Destruir Infraestrutura Terraform (Manual)

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: "projects/159248096205/locations/global/workloadIdentityPools/github-pool-a3/providers/github-provider"
          service_account: "strapi-deployer@sound-dialect-458215-j9.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="strapi_image=dummy" -lock-timeout=15m
        working-directory: ./terraform