# .github/workflows/docker-build.yml
# Workflow para build e push de imagem Docker para Google Container Registry
# Projeto: DevOps UNISATC A3 - Strapi Application

name: 🐳 Docker Build & Push

on:
  push:
    branches: 
      - master
    tags: [ 'v*' ]
  pull_request:
    branches: 
      - master
  workflow_dispatch:

# Variáveis de ambiente para todo o workflow
env:
  # Variáveis de configuração, o PROJECT_ID será obtido após a autenticação
  GCP_REGION: southamerica-east1
  ARTIFACT_HOSTNAME: southamerica-east1-docker.pkg.dev
  GCR_HOSTNAME: gcr.io
  IMAGE_NAME: devops-unisatc-a3-strapi
  DOCKERFILE_PATH: ./Dockerfile
  # Credenciais para o Workload Identity Federation
  GCP_SERVICE_ACCOUNT: strapi-deployer@sound-dialect-458215-j9.iam.gserviceaccount.com
  WIF_POOL: github-pool-a3
  WIF_PROVIDER: github-provider
  GCP_PROJECT_NUMBER: 159248096205

jobs:
  build-test-and-push:
    name: 🏗️ Build, Test & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Authenticate to Google Cloud
        id: auth # Damos um ID a este passo para usar suas saídas
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: "projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIF_POOL }}/providers/${{ env.WIF_PROVIDER }}"
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: 🐳 Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.ARTIFACT_HOSTNAME }} --quiet

      - name: 🏷️ Generate Image Tag
        id: meta
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            IMAGE_TAG=${GITHUB_REF#refs/tags/}
          else
            IMAGE_TAG="${GITHUB_SHA::8}"
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: 🏗️ Build Docker image
        id: build_image
        run: |
          # Constrói o nome completo da imagem AQUI, usando a saída do passo de autenticação
          IMAGE_FULL_NAME="${{ env.ARTIFACT_HOSTNAME }}/${{ steps.auth.outputs.project_id }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          
          # Salva o nome completo para ser usado nos passos seguintes
          echo "IMAGE_FULL_NAME=$IMAGE_FULL_NAME" >> $GITHUB_ENV
          
          echo "Building image: $IMAGE_FULL_NAME"
          docker build -t "$IMAGE_FULL_NAME" --file ${{ env.DOCKERFILE_PATH }} .

      - name: 🧪 Test Docker image (Smoke Test)
        id: smoke_test
        continue-on-error: true
        run: |
          echo "🧪 Iniciando teste de fumaça para a imagem: ${{ env.IMAGE_FULL_NAME }}"
          docker run -d --name strapi-test \
            -p 1337:1337 \
            -e NODE_ENV=development \
            -e DATABASE_CLIENT=sqlite \
            -e DATABASE_FILENAME=.tmp/test.db \
            -e JWT_SECRET=test-jwt-secret-dummy-value-for-testing \
            -e ADMIN_JWT_SECRET=test-admin-jwt-secret-dummy-value-for-testing \
            -e APP_KEYS='testkey1,testkey2,testkey3,testkey4' \
            -e API_TOKEN_SALT=test-api-token-salt \
            -e TRANSFER_TOKEN_SALT=test-transfer-token-salt \
            "${{ env.IMAGE_FULL_NAME }}"

          echo "⏳ Aguardando contêiner inicializar (até 90s)..."
          timeout 90s bash -c 'until curl -fs http://localhost:1337/admin/health/strapi; do echo "Aguardando..."; sleep 5; done'
          echo "✅ Teste de fumaça concluído com sucesso."

      - name: 🔍 Debug on Smoke Test Failure
        if: steps.smoke_test.outcome == 'failure'
        run: |
          echo "❌ Teste de fumaça falhou. Exibindo logs do contêiner..."
          docker logs strapi-test
          exit 1  # Força a falha do workflow

      - name: 🧹 Clean up test container
        if: always()
        run: |
          echo "🧹 Limpando contêiner de teste..."
          docker stop strapi-test || true
          docker rm strapi-test || true
      
      - name: 📤 Push image to Artifact Registry
        if: github.event_name != 'pull_request' # Só faz push se não for um PR
        run: |
          echo "📤 Enviando imagem para o registro: ${{ env.IMAGE_FULL_NAME }}"
          docker push "${{ env.IMAGE_FULL_NAME }}"

          # Se for a branch principal, também envia com a tag 'latest'
          if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            docker tag "${{ env.IMAGE_FULL_NAME }}" "${{ env.ARTIFACT_HOSTNAME }}/${{ steps.auth.outputs.project_id }}/${{ env.IMAGE_NAME }}:latest"
            docker push "${{ env.ARTIFACT_HOSTNAME }}/${{ steps.auth.outputs.project_id }}/${{ env.IMAGE_NAME }}:latest"
            echo "✅ Tag 'latest' adicionada e enviada."
          fi
